services:
  vue:
    container_name: vue
    build: ./
    ports:
      - 8080:8080
    volumes:
      - vue-volume:/var/www/html
    stdin_open: true
    privileged: true
    tty: true
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - vue-volume:/var/www/html
    depends_on:
      - vue
    privileged: true
    stdin_open: true
    tty: true

volumes:
  vue-volume:
